#!/usr/bin/env python

import json
import os
import socket
import sys
import re
import subprocess


def run(*cmd):
    process = subprocess.run(cmd, stdout=subprocess.PIPE, check=True)
    return process.stdout.decode().splitlines()


def run_bg(*cmd):
    subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def window_props(win_id):
    result = {
        "activities": [],
        "title": ""
    }

    sep = " = "
    for line in run("xprop", "-id", win_id):
        if sep not in line:
            continue

        name, value = line.split(sep, 1)

        if name == "_KDE_NET_WM_ACTIVITIES(STRING)":
            result["activities"] = value.strip('"').split(",")
        elif name == "WM_NAME(STRING)":
            result["title"] = value.strip('"')

    return result


def extract_session(title):
    match = re.search(r'qutebrowser\s*\[(.*)\]$', title)

    if not match:
        return None

    return match.group(1)


def open_through_socket(session, url):
    sockdir = "/run/user/{}/qutebrowser/{}/runtime".format(os.getuid(), session)
    sockfile = os.path.join(sockdir, os.listdir(sockdir)[0])

    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.connect(sockfile)

    sock.sendall(json.dumps({
        "args": [url],
        "target_arg": None,
        "version": "1.0.4",
        "protocol_version": 1,
        "cwd": os.getenv("PWD")
    }).encode() + b"\n")


if __name__ == "__main__":
    url = sys.argv[1]
    windows = run("wmctrl", "-l")
    current_activity = run("qdbus", "org.kde.ActivityManager", "/ActivityManager/Activities", "CurrentActivity")[0]

    for line in windows:
        win_id, *_ = line.split()
        props = window_props(win_id)

        if current_activity in props["activities"]:
            session = extract_session(props["title"])

            if session is not None:
                open_through_socket(session, url)
                sys.exit(0)

    activity_name = run("qdbus", "org.kde.ActivityManager", "/ActivityManager/Activities", "ActivityName", current_activity)[0]
    run_bg("qb", activity_name.replace(" ", ""), url)

