[settings]
experimental = true
disable_hints = ["python_multi"]
idiomatic_version_file_enable_tools = []

[settings.github]
credential_command = "gh auth token"

[hooks]
cd = """
sync-configs-to-worktree "$MISE_ORIGINAL_CWD"
"""

[tools]
actionlint = "latest"
stylua = "latest"
pandoc = "latest"
"github:apify/apify-cli" = { version = "1", asset_pattern = "apify-*-linux-x64" }
"github:michel-kraemer/zsh-patina" = { version = "1" }
"pipx:basedpyright" = { version = "1" }
usage = "latest"
uv = "latest"
"github:can1357/oh-my-pi" = "latest"
